name: lms_finanzen_v1_0
description: "Eine Business-Management-App für LMS Finanzen"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/lenzerheide_logo.gif
    - .env  # Füge die .env-Datei wieder als Asset hinzu

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  open_file: ^3.3.2
  intl: ^0.19.0
  path: ^1.8.3
  http: ^1.2.4
  syncfusion_flutter_xlsio: ^26.2.11
  share_plus: ^10.0.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  file_picker: ^8.1.3
  file_selector: ^1.0.3
  app_links: ^6.4.0
  image_picker: ^1.1.2
  pdf: ^3.11.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    remove_alpha: true