// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHKtUJOc-PXp0rznkmhONUl4ZrfQ0riC8',
    appId: '1:422661599043:web:f0554500d40de8771909f6',
    messagingSenderId: '422661599043',
    projectId: 'lms-finanzen',
    authDomain: 'lms-finanzen.firebaseapp.com',
    storageBucket: 'lms-finanzen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FFJBL9zvjKfHFJ-hKdG08Kw7pLeFeg4',
    appId: '1:422661599043:android:b8627a8d5a97c0c31909f6',
    messagingSenderId: '422661599043',
    projectId: 'lms-finanzen',
    storageBucket: 'lms-finanzen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2w9aR1wFFjUUiZ3g-2V0oP9TeqWOFIHc',
    appId: '1:422661599043:ios:189105535798db311909f6',
    messagingSenderId: '422661599043',
    projectId: 'lms-finanzen',
    storageBucket: 'lms-finanzen.firebasestorage.app',
    iosBundleId: 'com.example.lmsFinanzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2w9aR1wFFjUUiZ3g-2V0oP9TeqWOFIHc',
    appId: '1:422661599043:ios:356a9a919389e65a1909f6',
    messagingSenderId: '422661599043',
    projectId: 'lms-finanzen',
    storageBucket: 'lms-finanzen.firebasestorage.app',
    iosBundleId: 'com.example.lmsFinanzenV10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHKtUJOc-PXp0rznkmhONUl4ZrfQ0riC8',
    appId: '1:422661599043:web:f5d8d1ed41ffaf831909f6',
    messagingSenderId: '422661599043',
    projectId: 'lms-finanzen',
    authDomain: 'lms-finanzen.firebaseapp.com',
    storageBucket: 'lms-finanzen.firebasestorage.app',
  );

}